package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.SequenceDO;
import java.util.List;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Feb 06 20:53:20 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Feb 06 20:53:20 CST 2020
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Feb 06 20:53:20 CST 2020
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Feb 06 20:53:20 CST 2020
     */
    List<SequenceDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Thu Feb 06 20:53:20 CST 2020
     */
    int updateByPrimaryKey(SequenceDO record);
    SequenceDO getSequenceByName(String name);
}